import datetime
from datetime import date, time
from typing import Any, Self

from growattServer.async_base_api import AsyncGrowattApi
from growattServer.base_api import Timespan
from growattServer.open_api_v1.devices import ParameterValue
from growattServer.open_api_v1.devices.abstract_device import AbstractDevice
from growattServer.open_api_v1.devices.async_min import AsyncMin
from growattServer.open_api_v1.devices.async_sph import AsyncSph

class AsyncOpenApiV1(AsyncGrowattApi):
    _min_class: type[AsyncMin]
    _sph_class: type[AsyncSph]
    api_url: str

    def __init__(self, token: str, session: Any = None, timeout: float | None = ...) -> None: ...

    async def v1_request(self, method: str, endpoint: str, *, params: dict[str, Any] | None = None, data: dict[str, Any] | None = None, operation_name: str = ...) -> dict[str, Any]: ...

    # V1 API methods (from _OpenApiV1Base)
    async def plant_list(self) -> dict[str, Any]: ...  # type: ignore[override]
    async def plant_details(self, plant_id: int) -> dict[str, Any]: ...
    async def plant_energy_overview(self, plant_id: int) -> dict[str, Any]: ...
    async def plant_power_overview(self, plant_id: int, day: str | date | None = None) -> dict[str, Any]: ...
    async def plant_energy_history(self, plant_id: int, start_date: date | None = None, end_date: date | None = None, time_unit: str = ..., page: int | None = None, perpage: int | None = None) -> dict[str, Any]: ...
    async def device_list(self, plant_id: int | str) -> dict[str, Any]: ...  # type: ignore[override]
    def get_device(self, device_sn: str, device_type: int) -> AbstractDevice | None: ...
    async def min_detail(self, device_sn: str) -> dict[str, Any]: ...
    async def min_energy(self, device_sn: str) -> dict[str, Any]: ...
    async def min_energy_history(self, device_sn: str, start_date: date | None = None, end_date: date | None = None, timezone: str | None = None, page: int | None = None, limit: int | None = None) -> dict[str, Any]: ...
    async def min_settings(self, device_sn: str) -> dict[str, Any]: ...
    async def min_read_parameter(self, device_sn: str, parameter_id: str, start_address: int | None = None, end_address: int | None = None) -> dict[str, Any]: ...
    async def min_write_parameter(self, device_sn: str, parameter_id: str, parameter_values: ParameterValue | None = None) -> dict[str, Any]: ...
    async def min_write_time_segment(self, device_sn: str, segment_id: int, batt_mode: int, start_time: time, end_time: time, enabled: bool = ...) -> dict[str, Any]: ...
    async def min_read_time_segments(self, device_sn: str, settings_data: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...
    async def sph_detail(self, device_sn: str) -> dict[str, Any]: ...
    async def sph_energy(self, device_sn: str) -> dict[str, Any]: ...
    async def sph_energy_history(self, device_sn: str, start_date: date | None = None, end_date: date | None = None, timezone: str | None = None, page: int | None = None, limit: int | None = None) -> dict[str, Any]: ...
    async def sph_read_parameter(self, device_sn: str, parameter_id: str | None = None, start_address: int | None = None, end_address: int | None = None) -> dict[str, Any]: ...
    async def sph_write_parameter(self, device_sn: str, parameter_id: str, parameter_values: ParameterValue | None = None) -> dict[str, Any]: ...
    async def sph_write_ac_charge_times(self, device_sn: str, charge_power: int, charge_stop_soc: int, mains_enabled: bool, periods: list[dict[str, Any]]) -> dict[str, Any]: ...
    async def sph_write_ac_discharge_times(self, device_sn: str, discharge_power: int, discharge_stop_soc: int, periods: list[dict[str, Any]]) -> dict[str, Any]: ...
    async def sph_read_ac_charge_times(self, device_sn: str, settings_data: dict[str, Any] | None = None) -> dict[str, Any]: ...
    async def sph_read_ac_discharge_times(self, device_sn: str, settings_data: dict[str, Any] | None = None) -> dict[str, Any]: ...

    # Inherited from AsyncGrowattApi (legacy API methods)
    async def plant_detail(self, plant_id: str, timespan: Timespan, date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def plant_list_two(self) -> list[dict[str, Any]]: ...
    async def inverter_data(self, inverter_id: str, date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def inverter_detail(self, inverter_id: str) -> dict[str, Any]: ...
    async def inverter_detail_two(self, inverter_id: str) -> dict[str, Any]: ...
    async def tlx_system_status(self, plant_id: str, tlx_id: str) -> dict[str, Any]: ...
    async def tlx_energy_overview(self, plant_id: str, tlx_id: str) -> dict[str, Any]: ...
    async def tlx_energy_prod_cons(self, plant_id: str, tlx_id: str, timespan: Timespan = ..., date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def tlx_data(self, tlx_id: str, date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def tlx_detail(self, tlx_id: str) -> dict[str, Any]: ...
    async def tlx_params(self, tlx_id: str) -> dict[str, Any]: ...
    async def tlx_all_settings(self, tlx_id: str) -> dict[str, Any] | None: ...
    async def tlx_enabled_settings(self, tlx_id: str) -> dict[str, Any]: ...
    async def tlx_battery_info(self, serial_num: str) -> dict[str, Any]: ...
    async def tlx_battery_info_detailed(self, plant_id: str, serial_num: str) -> dict[str, Any]: ...
    async def mix_info(self, mix_id: str, plant_id: str | None = None) -> dict[str, Any]: ...
    async def mix_totals(self, mix_id: str, plant_id: str) -> dict[str, Any]: ...
    async def mix_system_status(self, mix_id: str, plant_id: str) -> dict[str, Any]: ...
    async def mix_detail(self, mix_id: str, plant_id: str, timespan: Timespan = ..., date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def get_mix_inverter_settings(self, serial_number: str) -> dict[str, Any]: ...
    async def dashboard_data(self, plant_id: str, timespan: Timespan = ..., date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def plant_settings(self, plant_id: str) -> dict[str, Any]: ...
    async def storage_detail(self, storage_id: str) -> dict[str, Any]: ...
    async def storage_params(self, storage_id: str) -> dict[str, Any]: ...
    async def storage_energy_overview(self, plant_id: str, storage_id: str) -> dict[str, Any]: ...
    async def inverter_list(self, plant_id: str) -> list[dict[str, Any]]: ...
    async def plant_info(self, plant_id: str) -> dict[str, Any]: ...
    async def plant_energy_data(self, plant_id: str) -> dict[str, Any]: ...
    async def is_plant_noah_system(self, plant_id: str) -> dict[str, Any]: ...
    async def noah_system_status(self, serial_number: str) -> dict[str, Any]: ...
    async def noah_info(self, serial_number: str) -> dict[str, Any]: ...
    async def update_inverter_setting(self, serial_number: str, setting_type: str, default_parameters: dict[str, Any], parameters: dict[str, Any] | list[Any]) -> dict[str, Any]: ...
    async def update_mix_inverter_setting(self, serial_number: str, setting_type: str, parameters: dict[str, Any] | list[Any]) -> dict[str, Any]: ...
    async def update_ac_inverter_setting(self, serial_number: str, setting_type: str, parameters: dict[str, Any] | list[Any]) -> dict[str, Any]: ...
    async def update_tlx_inverter_time_segment(self, serial_number: str, segment_id: int, batt_mode: int, start_time: datetime.time, end_time: datetime.time, enabled: bool) -> dict[str, Any]: ...
    async def update_tlx_inverter_setting(self, serial_number: str, setting_type: str, parameter: dict[str, Any] | list[Any] | str) -> dict[str, Any]: ...
    async def update_noah_settings(self, serial_number: str, setting_type: str, parameters: dict[str, Any] | list[Any]) -> dict[str, Any]: ...
    async def update_classic_inverter_setting(self, default_parameters: dict[str, Any], parameters: dict[str, Any] | list[Any]) -> dict[str, Any]: ...
    async def set_classic_inverter_active_power_rate(self, serial_number: str, power_rate: int) -> dict[str, Any]: ...
    async def set_classic_inverter_on_off(self, serial_number: str, enabled: bool) -> dict[str, Any]: ...
    async def classic_inverter_info(self, device_sn: str) -> dict[str, Any]: ...

    # Context manager (from AsyncGrowattApi)
    async def aclose(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, *args: object) -> None: ...
    async def login(self, username: str, password: str, is_password_hashed: bool = False) -> dict[str, Any]: ...
    async def update_plant_settings(self, plant_id: str, changed_settings: dict[str, Any], current_settings: dict[str, Any] | None = None) -> dict[str, Any]: ...
