"""Type stubs for async Growatt API client."""

from __future__ import annotations

import datetime
from collections.abc import Callable
from typing import Any, TypeVar

import httpx

from .base_api import Timespan

_T = TypeVar("_T")


class AsyncGrowattApi:
    server_url: str
    agent_identifier: str
    session: httpx.AsyncClient
    _owns_session: bool

    def __init__(self, add_random_user_id: bool = False, agent_identifier: str | None = None, session: httpx.AsyncClient | None = None, timeout: float | None = ...) -> None: ...
    def get_url(self, page: str) -> str: ...

    async def _request(self, method: str, url: str, *, params: dict[str, Any] | None = None, data: dict[str, Any] | None = None, follow_redirects: bool | None = None, extract: Callable[[Any], _T] | None = None, text: bool = False) -> Any: ...

    async def aclose(self) -> None: ...
    async def __aenter__(self) -> AsyncGrowattApi: ...
    async def __aexit__(self, *args: object) -> None: ...

    # Methods from _GrowattApiBase re-declared as async
    async def plant_list(self, user_id: str) -> dict[str, Any]: ...
    async def login(self, username: str, password: str, is_password_hashed: bool = False) -> dict[str, Any]: ...
    async def device_list(self, plant_id: str) -> list[dict[str, Any]]: ...
    async def update_plant_settings(self, plant_id: str, changed_settings: dict[str, Any], current_settings: dict[str, Any] | None = None) -> dict[str, Any]: ...

    # All inherited methods from _GrowattApiBase
    async def plant_detail(self, plant_id: str, timespan: Timespan, date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def plant_list_two(self) -> list[dict[str, Any]]: ...
    async def inverter_data(self, inverter_id: str, date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def inverter_detail(self, inverter_id: str) -> dict[str, Any]: ...
    async def inverter_detail_two(self, inverter_id: str) -> dict[str, Any]: ...
    async def tlx_system_status(self, plant_id: str, tlx_id: str) -> dict[str, Any]: ...
    async def tlx_energy_overview(self, plant_id: str, tlx_id: str) -> dict[str, Any]: ...
    async def tlx_energy_prod_cons(self, plant_id: str, tlx_id: str, timespan: Timespan = ..., date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def tlx_data(self, tlx_id: str, date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def tlx_detail(self, tlx_id: str) -> dict[str, Any]: ...
    async def tlx_params(self, tlx_id: str) -> dict[str, Any]: ...
    async def tlx_all_settings(self, tlx_id: str) -> dict[str, Any] | None: ...
    async def tlx_enabled_settings(self, tlx_id: str) -> dict[str, Any]: ...
    async def tlx_battery_info(self, serial_num: str) -> dict[str, Any]: ...
    async def tlx_battery_info_detailed(self, plant_id: str, serial_num: str) -> dict[str, Any]: ...
    async def mix_info(self, mix_id: str, plant_id: str | None = None) -> dict[str, Any]: ...
    async def mix_totals(self, mix_id: str, plant_id: str) -> dict[str, Any]: ...
    async def mix_system_status(self, mix_id: str, plant_id: str) -> dict[str, Any]: ...
    async def mix_detail(self, mix_id: str, plant_id: str, timespan: Timespan = ..., date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def get_mix_inverter_settings(self, serial_number: str) -> dict[str, Any]: ...
    async def dashboard_data(self, plant_id: str, timespan: Timespan = ..., date: datetime.datetime | None = None) -> dict[str, Any]: ...
    async def plant_settings(self, plant_id: str) -> dict[str, Any]: ...
    async def storage_detail(self, storage_id: str) -> dict[str, Any]: ...
    async def storage_params(self, storage_id: str) -> dict[str, Any]: ...
    async def storage_energy_overview(self, plant_id: str, storage_id: str) -> dict[str, Any]: ...
    async def inverter_list(self, plant_id: str) -> list[dict[str, Any]]: ...
    async def _get_all_devices(self, plant_id: str) -> list[dict[str, Any]]: ...
    async def plant_info(self, plant_id: str) -> dict[str, Any]: ...
    async def plant_energy_data(self, plant_id: str) -> dict[str, Any]: ...
    async def is_plant_noah_system(self, plant_id: str) -> dict[str, Any]: ...
    async def noah_system_status(self, serial_number: str) -> dict[str, Any]: ...
    async def noah_info(self, serial_number: str) -> dict[str, Any]: ...
    async def update_inverter_setting(self, serial_number: str, setting_type: str, default_parameters: dict[str, Any], parameters: dict[str, Any] | list[Any]) -> dict[str, Any]: ...
    async def update_mix_inverter_setting(self, serial_number: str, setting_type: str, parameters: dict[str, Any] | list[Any]) -> dict[str, Any]: ...
    async def update_ac_inverter_setting(self, serial_number: str, setting_type: str, parameters: dict[str, Any] | list[Any]) -> dict[str, Any]: ...
    async def update_tlx_inverter_time_segment(self, serial_number: str, segment_id: int, batt_mode: int, start_time: datetime.time, end_time: datetime.time, enabled: bool) -> dict[str, Any]: ...
    async def update_tlx_inverter_setting(self, serial_number: str, setting_type: str, parameter: dict[str, Any] | list[Any] | str) -> dict[str, Any]: ...
    async def update_noah_settings(self, serial_number: str, setting_type: str, parameters: dict[str, Any] | list[Any]) -> dict[str, Any]: ...
    async def update_classic_inverter_setting(self, default_parameters: dict[str, Any], parameters: dict[str, Any] | list[Any]) -> dict[str, Any]: ...
    async def set_classic_inverter_active_power_rate(self, serial_number: str, power_rate: int) -> dict[str, Any]: ...
    async def set_classic_inverter_on_off(self, serial_number: str, enabled: bool) -> dict[str, Any]: ...
    async def classic_inverter_info(self, device_sn: str) -> dict[str, Any]: ...
