name: mypy
on:
  - push
  - pull_request

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install mypy types-requests
      - run: mypy --ignore-missing-imports growattServer/
